import Head from 'next/head';
import { Header } from '@/components/header/header';
import { LoginForm } from '@/components/forms/login-form';

export default function Login() {
    return (
        <>
            <Head>
                <title>Hotel Booking Aggregator ~ Вход</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/logo.svg" />
            </Head>
            <Header />
            <main className="container mx-auto px-6">
                <div className="w-full min-h-screen lg:py-20">
                    <LoginForm />
                </div>
            </main>
        </>
    );
}