version: "3.9"
services: 
  hotel-aggregator-front:
    build: ./
    container_name: hotel-aggregator-front
    ports:
      - "${PORT}:${PORT_IN}"
    env_file: 
      - .env.local  # Используем файл .env.local
    environment:      
      - NODE_ENV=${NEXT_PUBLIC_NODE_ENV}
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
      - NEXT_PUBLIC_BASE_PICTURES_URL=${NEXT_PUBLIC_BASE_PICTURES_URL}
      - NEXT_PUBLIC_BASE_API_URL=${NEXT_PUBLIC_BASE_API_URL}
      - NEXT_PUBLIC_BASE_VIDEO_URL=${NEXT_PUBLIC_BASE_VIDEO_URL}
      - NEXT_PUBLIC_BASE_IMAGES_URL=${NEXT_PUBLIC_BASE_IMAGES_URL}
      - NEXT_PUBLIC_YM_ACCOUNT=${NEXT_PUBLIC_YM_ACCOUNT}
      - NEXT_PUBLIC_YM_API_KEY=${NEXT_PUBLIC_YM_API_KEY}
      - NEXT_PUBLIC_MAX_FILES_SIZE=${NEXT_PUBLIC_MAX_FILES_SIZE}
      - NEXT_PUBLIC_MAX_FILES=${NEXT_PUBLIC_MAX_FILES}
