version: "3.9"
services: 
  hotel-aggregator-front:
    build: ./
    container_name: hotel-aggregator-front
    ports:
      - 80:${PORT}
    environment:      
      - PORT=${PORT}
    command: sh -c "cd /app; rm -rf node_modules; npm install --force; npm run build; npm run start"
