import { 
    faWifi, faUtensils, faDumbbell, faSpa, faPaw, faParking, faSwimmer, 
    faSmokingBan, faConciergeBell, faShuttleVan, faTv, faBath, faChild, 
    faLuggageCart, faSnowflake, faMusic, faBiking, 
    faCoffee, faFan, faMicrophone, faCar, faSkiing, faDog, faHiking, 
    faUmbrellaBeach, faClinicMedical, faPlug, faBusinessTime, faHandshake, 
    faBinoculars, faChair, faBroom, faThermometerHalf, faBasketballBall, 
    faMapMarkerAlt, faWind, faFireAlt, faBed, faTableTennis, 
    faCocktail, faBell, faBaby, faBeer, 
    faSwimmingPool, faWarehouse,  faTrain, 
    faWineBottle, faFish, faChurch, faTshirt, faFirstAid, faLock, faHeart, 
    faBan, faSoap, faElevator, faExchangeAlt,
    faInfoCircle, faVolumeMute, 
    faBullseye, faVial, faShieldVirus, faWheelchair, faTicketAlt, faExclamationCircle, 
    faRunning, faMicrochip, faProcedures, faKey, faFax, faBox, faShip, 
    faHome, faNewspaper, faWater, faCouch,  faCompactDisc, 
    faClipboard, faUserMd, faDesktop, faBug,  faLeaf, faPlane, 
    faMoneyBill, faBurn, faClock, faSocks, faDoorOpen, faUserTie, 
    faPaintBrush,  faUniversity, faHeartbeat, faGamepad, 
    faUserShield, faGlassCheers, faIcicles, faSun, faCookie, faHorseHead, 
    faPhone, faStar, faUser, faLandmark, faLanguage,  faShoppingBag,
    faStream, faSmoking, faShoppingCart, faGolfBall, faFireExtinguisher, faHotTub,
    faBowlingBall, faSnowboarding, faGift, faShower, faBook, faDice, faTaxi, faToilet, faCopy
} from '@fortawesome/free-solid-svg-icons';

  
const amenityIconMap = {
    'Трансфер до пляжа (бесплатно)': faShuttleVan,
    'Крытый бассейн': faSwimmingPool,
    'Возможен полный пансион': faUtensils,
    'Squash': faTableTennis,
    'Радио': faMusic,
    'The winery': faWineBottle,
    'Solarium': faSun,
    'Children\'s pool': faChild,
    'Tour desk': faInfoCircle,
    'Skiing': faSkiing,
    'The beach is nearby': faUmbrellaBeach,
    'Picnic area': faBasketballBall,
    'Йога': faSpa,
    'Номера со звукоизоляцией': faVolumeMute,
    'Дартс': faBullseye,
    'Люкс для новобрачных': faHeart,
    'Бесплатные детские кроватки/люльки': faBaby,
    'ПЦР-тестирование на COVID-19': faVial,
    'Детское меню': faUtensils,
    'Бар оборудован для доступа гостей на инвалидных креслах': faWheelchair,
    'Паровая баня': faStream,
    'Номера для курящих': faSmoking,
    'Продажа билетов': faTicketAlt,
    'Чайник': faCoffee,
    'Barbecue area': faBurn,
    'Darts': faBullseye,
    'Music Center': faMusic,
    'The press': faNewspaper,
    'Free shuttle service to the surrounding area': faShuttleVan,
    'Transfer to the shopping center': faShoppingCart,
    'на турецком': faLanguage,
    'Фен': faWind,
    'Lack of elevators': faExclamationCircle,
    'Kitchen': faUtensils,
    'Accommodation with pets (less than 5 kg)': faDog,
    'Recreational activities': faRunning,
    'Микроволновая печь': faMicrochip,
    'Трансфер до торгового центра': faShoppingCart,
    'For guests with disabilities': faWheelchair,
    'Rooms for allergy sufferers': faProcedures,
    'Душ': faShower,
    'Спа-центр': faSpa,
    'in Japanese': faLanguage,
    'Ticket sales': faTicketAlt,
    'Аквапарк': faWater,
    'Rooftop pool': faSwimmingPool,
    'Полотенца для пляжа/бассейна': faUmbrellaBeach,
    'Ice rink': faIcicles,
    'in Korean': faLanguage,
    'Children\'s Club': faChild,
    'Private check-in and check-out': faKey,
    'Free airport shuttle': faShuttleVan,
    'Удобства для бассейна': faSwimmer,
    'Restaurant': faUtensils,
    'Fax': faFax,
    'First Aid kit': faFirstAid,
    'Washer': faSoap,
    'Бассейн с подогревом': faThermometerHalf,
    'Трансфер от/до аэропорта': faPlane,
    'Запирающийся шкафчик': faLock,
    'Patio': faCouch,
    'Индивидуальная регистрация заезда и отъезда': faKey,
    'in Polish': faLanguage,
    'Reception desk': faConciergeBell,
    'Упакованные завтраки/обеды': faBox,
    'in Arabic': faLanguage,
    'Skiing outside the hotel': faSkiing,
    'in Russian': faLanguage,
    'Ping pong': faTableTennis,
    'Индивидуальные средства защиты для персонала': faShieldVirus,
    'Телевизор': faTv,
    'Transfer services': faShuttleVan,
    'The accommodation is suitable for families/children': faHome,
    'Radio': faMusic,
    'Бутилированная вода (за дополнительную плату)': faWater,
    'Сушилка': faWind,
    'Personal protective equipment for guests': faShieldVirus,
    'Free internet access': faWifi,
    'Телевизор в лобби': faTv,
    'Интернет в номере': faWifi,
    'Туалетные принадлежности': faSoap,
    'Meals in individual packaging': faBox,
    'Бесплатный трансфер от/до аэропорта': faPlane,
    'Плавание на лодках': faShip,
    'Смежные номера': faDoorOpen,
    'Парковка': faParking,
    'Free parking': faParking,
    'Mini golf': faGolfBall,
    'на французском': faLanguage,
    'Fitness Center': faDumbbell,
    'Размещение подходит для семей/детей': faHome,
    'Ski access to the hotel': faSkiing,
    'Сувенирный магазин': faGift,
    'Бассейн на крыше': faSwimmingPool,
    'Отсутствие лифтов': faExclamationCircle,
    'You can smoke': faSmoking,
    'Детектор дыма': faBurn,
    'Tennis court': faTableTennis,
    'Бесплатный трансфер': faShuttleVan,
    'A microwave': faMicrochip,
    'Гладильные услуги': faBroom,
    'Удобства для водных видов спорта': faSwimmer,
    'Fire extinguisher': faFireExtinguisher,
    'на немецком': faLanguage,
    'Ski slope nearby': faSkiing,
    'Часовня': faChurch,
    'Jacuzzi': faHotTub,
    'Врач': faUserMd,
    'Дежурный врач': faUserMd,
    'Круглосуточная стойка регистрации': faConciergeBell,
    'Pets (over 5 kg) are not allowed': faBan,
    'Развлечения на воде': faWater,
    'Компьютер': faDesktop,
    'Теннисный корт': faTableTennis,
    'Free Wi-Fi': faWifi,
    'Snorkeling': faWater,
    'Wi-fi в отеле': faWifi,
    'Обмен валюты': faExchangeAlt,
    'Beach/Pool towels': faUmbrellaBeach,
    'Сейф (в номере)': faLock,
    'Spa services': faSpa,
    'Wi-Fi': faWifi,
    'Bowling': faBowlingBall,
    'Душ/Ванна': faBath,
    'The restaurant is equipped for wheelchair access': faWheelchair,
    'Hunting': faBinoculars,
    'The shops': faShoppingBag,
    'Парковка рядом с отелем': faParking,
    'Library': faBook,
    'Размещение с домашними животными': faPaw,
    'Parking next to the hotel': faParking,
    'Airport transfer': faPlane,
    'Лифт': faElevator,
    'Table tennis': faTableTennis,
    'Гладильные принадлежности': faBroom,
    'Питание в индивидуальной упаковке': faBox,
    'Garden': faLeaf,
    'Дайвинг': faSwimmer,
    'The doctor on duty': faUserMd,
    'Internet in the room': faWifi,
    'Sun terrace': faSun,
    'ATM machine': faMoneyBill,
    'Бесплатное размещение с домашними животными': faPaw,
    'Баня': faThermometerHalf,
    'Bathrobe (on request)': faBath,
    'Ресторан': faUtensils,
    'Restaurant (buffet)': faUtensils,
    'Barrier-free access': faWheelchair,
    'Трансфер до аэропорта': faPlane,
    'Doctor': faUserMd,
    'Fridge': faWineBottle,
    'Диетическое меню (по запросу)': faUtensils,
    'Бесплатный интернет': faWifi,
    'Packed lunches': faBox,
    'Safety Memo': faClipboard,
    'in Turkish': faLanguage,
    'TV': faTv,
    'Лыжный трансфер': faShuttleVan,
    'Детский клуб': faChild,
    'Бесплатная парковка': faParking,
    'на испанском': faLanguage,
    'Iron': faChair,
    'Cafe': faCoffee,
    'The Chapel': faChurch,
    'Сноуборд': faSnowboarding,
    'Free parking near the hotel': faParking,
    'Детская игровая площадка': faChild,
    'Парковка (по запросу)': faParking,
    'Massage (for an additional fee)': faSpa,
    'Депозитные ячейки': faLock,
    'на португальском': faLanguage,
    'Виндсерфинг': faWater,
    'Конференц-зал': faHandshake,
    'Патио': faCouch,
    'Hammam': faHotTub,
    'Пеший туризм': faHiking,
    'Температурный контроль для персонала': faThermometerHalf,
    'Seasonal outdoor pool': faSwimmingPool,
    'Гладильные принадлежности (по запросу)': faBroom,
    'Усиленные меры дезинфекции': faShieldVirus,
    'Детские телеканалы': faTv,
    'Parking (on request)': faParking,
    'Экскурсионное бюро': faInfoCircle,
    'Массаж (за дополнительную плату)': faSpa,
    'Халат (по запросу)': faBath,
    'Play room': faGamepad,
    'Free transfer from/to the railway station': faTrain,
    'Billiard': faBowlingBall,
    'Сквош': faTableTennis,
    'Сезонный открытый бассейн': faSwimmingPool,
    'There is no parking': faBan,
    'Snowmobile and ATV rental': faSnowflake,
    'Internet access': faWifi,
    'Открытый бассейн': faSwimmingPool,
    'Steam bath': faHotTub,
    'in English': faLanguage,
    'Терраса': faSun,
    'Огнетушитель': faFireExtinguisher,
    'Температурный контроль для гостей': faThermometerHalf,
    'Бассейн': faSwimmingPool,
    'Возможен полупансион': faUtensils,
    'Horse riding': faHorseHead,
    'Общая кухня': faUtensils,
    'Smoking is allowed': faSmoking,
    'Ранняя регистрация заезда': faClock,
    'Video and computer equipment rental': faDesktop,
    'Trouser Press': faTshirt,
    'Hair dryer (on request)': faWind,
    'Мебель на улице': faCouch,
    'Стойка регистрации': faConciergeBell,
    'Windsurfing': faWater,
    'Услуга «звонок - будильник»': faBell,
    'Домофон': faDoorOpen,
    'Ресторан («шведский стол»)': faUtensils,
    'Transfer to the surrounding area': faShuttleVan,
    'Organization of meetings and banquets': faHandshake,
    'Private beach': faUmbrellaBeach,
    'Детские кроватки/люльки': faBaby,
    'Прокат снегоходов и квадроциклов': faSnowflake,
    'Parking space': faParking,
    'Поле для гольфа (в пределах 3 км)': faGolfBall,
    'Завтрак «шведский стол»': faUtensils,
    'Удобства для гостей с ограниченными физическими возможностями': faWheelchair,
    'Cable TV': faTv,
    'Музей': faLandmark,
    'Pets are not allowed': faBan,
    'Casino': faDice,
    'Хранение багажа': faLuggageCart,
    'Heated swimming pool': faThermometerHalf,
    'Трансферные услуги': faShuttleVan,
    'Бар': faCocktail,
    'Ironing services': faBroom,
    'Стиральная машина': faSoap,
    'Открытый бассейн с подогревом': faThermometerHalf,
    'Рыбалка': faFish,
    'Safe deposit': faLock,
    'Частный пляж': faUmbrellaBeach,
    'Казино': faDice,
    'Shared kitchen': faUtensils,
    'Бесплатный трансфер от/до жд вокзала': faTrain,
    'Посудомоечная машина': faSoap,
    'Сезонный крытый бассейн': faSwimmingPool,
    'The Butler': faUserTie,
    'Outdoor swimming pool': faSwimmingPool,
    'Terrace': faSun,
    'Transfer from/to the railway station': faTrain,
    'Катание на лыжах за пределами территории отеля': faSkiing,
    'Bottled water (extra charge)': faWater,
    'Детский бассейн': faChild,
    'Караоке': faMicrophone,
    'Fax and photocopying services': faFax,
    'Мультиязычный персонал': faLanguage,
    'Бесплатная общественная парковка поблизости': faParking,
    'Бесплатный трансфер до порта': faShip,
    'Children\'s playground': faChild,
    'Accommodation with pets': faPaw,
    'Бесплатный трансфер по окрестностям': faShuttleVan,
    'Telephone': faPhone,
    'Early check-in': faClock,
    'Можно курить': faSmoking,
    'Clothes rack': faTshirt,
    'Москитная сетка': faBug,
    'Пинг-понг': faTableTennis,
    'Яхтинг': faShip,
    'Библиотека': faBook,
    'Free airport shuttle service': faPlane,
    'Connecting rooms': faDoorOpen,
    'Bank': faUniversity,
    'Dryer': faWind,
    'Safe deposit box (in the room)': faLock,
    'Conditioner': faSnowflake,
    'TV in the lobby': faTv,
    'Allowed with pets': faPaw,
    'Gym': faDumbbell,
    'Мини-бар': faBeer,
    'Охрана': faUserShield,
    'Будильник': faBell,
    'Винодельческое хозяйство': faWineBottle,
    'Free accommodation with pets': faPaw,
    'Прокат автомобилей': faCar,
    'Hiking': faHiking,
    'Late check-out': faClock,
    'Dry cleaning': faBroom,
    'Оборудование для встреч и презентаций': faHandshake,
    'Хаммам': faHotTub,
    'Ordering a taxi': faTaxi,
    'PCR testing for COVID-19': faVial,
    'Постельное белье': faBed,
    'Трансфер от аэропорта': faPlane,
    'Coffee machine': faCoffee,
    'Работают лифты для доступа к верхним этажам': faElevator,
    'Бесплатный трансфер до горнолыжного склона': faSkiing,
    'The hotel is non-smoking': faBan,
    'Wi-Fi in the hotel': faWifi,
    'Пресса': faNewspaper,
    'Entertainment on the water': faWater,
    'Free bike rental': faBiking,
    'Салон красоты': faSpa,
    'Сауна': faHotTub,
    'Expedited check-in and check-out': faClock,
    'Лыжная школа': faSkiing,
    'Кондиционер': faSnowflake,
    'Ускоренная регистрация заезда и выезда': faClock,
    'Barbecue facilities': faBurn,
    'Family Rooms': faHome,
    'Suitable for festive events': faGlassCheers,
    'Пляж рядом': faUmbrellaBeach,
    'Deposit boxes': faLock,
    'Кофемашина': faCoffee,
    'Smoking is prohibited in the entire territory': faBan,
    'Пресс для брюк': faTshirt,
    'Прокат велосипедов': faBiking,
    'Bathrobe': faBath,
    'Химчистка': faBroom,
    'Karaoke': faMicrophone,
    'Beach facilities': faUmbrellaBeach,
    'Ускоренная регистрация заезда': faClock,
    'Настольный теннис': faTableTennis,
    'Half board is possible': faUtensils,
    'Бесплатный прокат велосипедов': faBiking,
    'Intercom system': faPhone,
    '24-hour front desk': faConciergeBell,
    'Банкомат': faMoneyBill,
    'Children\'s TV channels': faTv,
    'Vending machine with snacks/drinks': faCookie,
    'Катание на лыжах': faSkiing,
    'Подходит для проведения праздничных мероприятий': faGlassCheers,
    'Завтрак': faUtensils,
    'Фен (по запросу)': faWind,
    'in French': faLanguage,
    'Торговый автомат с закусками/напитками': faCookie,
    'Fan': faFan,
    'Temperature control for guests': faThermometerHalf,
    'Luggage storage': faLuggageCart,
    'Холодильник': faWineBottle,
    'Ресторан оборудован для доступа гостей на инвалидных креслах': faWheelchair,
    'Подходит для детей': faChild,
    'Бутилированная вода': faWater,
    'Прокат видео- и компьютерной техники': faDesktop,
    'Equipment for meetings and presentations': faHandshake,
    'Room service': faConciergeBell,
    'Места для курения': faSmoking,
    'Ski School': faSkiing,
    'Массаж': faSpa,
    'Golf Course': faGolfBall,
    'Камера хранения': faLuggageCart,
    'Shoe cleaning': faBroom,
    'Teapot': faCoffee,
    'Bath': faBath,
    'Pets allowed (less than 5 kg) (extra charge)': faDog,
    'Парковка отсутствует': faBan,
    'Rooms with sound insulation': faVolumeMute,
    'Бар или ресторан': faUtensils,
    'Shower/Bath': faBath,
    'Камин': faFireAlt,
    'Общественный пляж': faUmbrellaBeach,
    'Currency exchange': faExchangeAlt,
    'на русском': faLanguage,
    'Seasonal indoor pool': faSwimmingPool,
    'Для гостей с ограниченными возможностями': faWheelchair,
    'Безбарьерный доступ': faWheelchair,
    'Fitness': faDumbbell,
    'Мини-кухня': faUtensils,
    'Тренажерный зал': faDumbbell,
    'Памятка по безопасности': faClipboard,
    'Катание на велосипеде': faBiking,
    'Отопление': faSnowflake,
    'Детские кроватки/люльки (за дополнительную плату)': faBaby,
    'Breakfast in the room': faUtensils,
    'Упакованные ланчи': faBox,
    'Non-smoking rooms': faSmokingBan,
    'Fishing': faFish,
    'Babysitting and child care services': faBaby,
    'на английском': faLanguage,
    'in Chinese': faLanguage,
    'Ночной клуб': faMusic,
    'Трансфер от/до жд вокзала': faTrain,
    'Smoking rooms': faSmoking,
    'Health Club': faHeartbeat,
    'Baby cots/cradles (extra charge)': faBaby,
    'in Spanish': faLanguage,
    'Outdoor heated swimming pool': faThermometerHalf,
    'Номера для аллергиков': faProcedures,
    'на арабском': faLanguage,
    'Bridal Suite': faHeart,
    'Free transfer to the port': faShip,
    'Concierge services': faConciergeBell,
    'Toilets with handrails': faToilet,
    'Free internet': faWifi,
    'Ironing facilities': faBroom,
    'Enhanced disinfection measures': faShieldVirus,
    'Wake-up service': faBell,
    'на итальянском': faLanguage,
    'Suitable for children': faChild,
    'Бесплатный доступ в интернет': faWifi,
    'Услуги няни и уход за детьми': faBaby,
    'DVD player': faCompactDisc,
    'in Italian': faLanguage,
    'Бесплатный Wi-Fi': faWifi,
    'Дополнительные меры против COVID-19': faShieldVirus,
    'in German': faLanguage,
    'Туалеты с поручнями': faToilet,
    'Bottled water': faWater,
    'Поздняя регистрация выезда': faClock,
    'VIP-удобства в номере': faStar,
    'Снэк-бар': faCookie,
    'Ski storage room': faSkiing,
    'Free public parking is available nearby': faParking,
    'Размещение с домашними животными (меньше 5 кг) (за дополнительную плату)': faDog,
    'Стойка для одежды': faTshirt,
    'Free transfer to the ski slope': faSkiing,
    'Free baby cots/cradles': faBaby,
    'Alarm': faBell,
    'Children\'s menu': faUtensils,
    'Бильярд': faBowlingBall,
    'Baby cots/cradles': faBaby,
    'Солярий': faSun,
    'Multilingual staff': faLanguage,
    'Smoke Detector': faBurn,
    'Организация встреч и банкетов': faHandshake,
    'Заказ такси': faTaxi,
    'Fireplace': faFireAlt,
    'Slippers': faSocks,
    'Площадка для пикника': faBasketballBall,
    'Ванна': faBath,
    'Сноркелинг': faWater,
    'Боулинг': faBowlingBall,
    'Wardrobe/Closet': faTshirt,
    'Ксерокс': faCopy,
    'Contactless check-in and/or check-out': faShieldVirus,
    'Elevator': faElevator,
    'Игровая комната': faGamepad,
    'Laptop safe': faLock,
    'Near the beach': faUmbrellaBeach,
    'Personal protective equipment for personnel': faShieldVirus,
    'Free tea/coffee': faCoffee,
    'Smoking areas': faSmoking,
    'in Portuguese': faLanguage,
    'Тапочки': faSocks,
    'Shower': faShower,
    'Bathhouse': faHotTub,
    'Трансфер по окрестностям': faShuttleVan,
    'Оздоровительный клуб': faHeartbeat,
    'Индивидуальные средства защиты для гостей': faShieldVirus,
    'Diving': faSwimmer,
    'Терраса для загара': faSun,
    'Expedited check-in': faClock,
    'Разрешено с домашними животными': faPaw,
    'Факс и ксерокс': faFax,
    'Golf course (within 3 km)': faGolfBall,
    'Трансфер до горнолыжного склона': faSkiing,
    'Халат': faBath,
    'Размещение с домашними животными (больше 5 кг) не допускается': faBan,
    'Каток': faIcicles,
    'Кухня': faUtensils,
    'The kitchenette': faUtensils,
    'Прокат лыжной экипировки': faSkiing,
    'Горнолыжный склон рядом': faSkiing,
    'Mini fridge': faWineBottle,
    'Чистка обуви': faBroom,
    'Ski transfer': faSkiing,
    'Номера для некурящих': faSmokingBan,
    'Услуги консьержа': faConciergeBell,
    'Прачечная': faBroom,
    'Flat-screen TV': faTv,
    'Laundry': faBroom,
    'Sale of ski passes': faTicketAlt,
    'Отель для некурящих': faBan,
    'VIP room amenities': faStar,
    'Cycling': faBiking,
    'Завтрак в номер': faUtensils,
    'Security': faUserShield,
    'Кафе': faCoffee,
    'Спа-услуги': faSpa,
    'Pharmacy': faClinicMedical,
    'Charging electric vehicles': faPlug,
    'Sauna': faHotTub,
    'Развлекательные мероприятия': faMusic,
    'Pool Bar': faCocktail,
    'Dishwasher': faSoap,
    'Музыкальный центр': faMusic,
    'Business Center': faBusinessTime,
    'Обслуживание номеров': faConciergeBell,
    'Дворецкий': faUserTie,
    'Ускоренная регистрация выезда': faClock,
    'Охота': faBinoculars,
    'Car rental': faCar,
    'Бесконтактная регистрация заезда и/или выезда': faShieldVirus,
    'Джакузи': faHotTub,
    'Transfer': faShuttleVan,
    'Сад': faLeaf,
    'Бесплатный чай/кофе': faCoffee,
    'Продажа горнолыжных абонементов': faTicketAlt,
    'Бесплатная парковка рядом с отелем': faParking,
    'Sailing': faShip,
    'Design Hotel': faPaintBrush,
    'Удобства для барбекю': faBurn,
    'Indoor heated swimming pool': faThermometerHalf,
    'Xerox': faCopy,
    'Badminton': faTableTennis,
    'на польском': faLanguage,
    'Full board is possible': faUtensils,
    'Сейф для ноутбука': faLock,
    'Трансфер': faShuttleVan,
    'Телевизор с плоским экраном': faTv,
    'на корейском': faLanguage,
    'Mosquito net': faBug,
    'Гараж': faWarehouse,
    'Семейные номера': faHome,
    'Transfer to the beach (free of charge)': faUmbrellaBeach,
    'Water park': faWater,
    'Breakfast': faUtensils,
    'Lockable locker': faLock,
    'Yoga': faSpa,
    'Bar or restaurant': faUtensils,
    'Boating': faShip,
    'Bed linen': faBed,
    'Удобства для пляжа': faUmbrellaBeach,
    'Мини-гольф': faGolfBall,
    'Верховая езда': faHorseHead,
    'Night club': faMusic,
    'Сейф': faLock,
    'Кабельное телевидение': faTv,
    'Бесплатный трансфер до аэропорта': faPlane,
    'Expedited check-out': faClock,
    'Packed breakfasts/lunches': faBox,
    'Курение разрешено': faSmoking,
    'For adults only': faUser,
    'Yachting': faShip,
    'Bar': faCocktail,
    'Фитнес-центр': faDumbbell,
    'Размещение с домашними животными (меньше 5 кг)': faDog,
    'Snowboard': faSnowboarding,
    'Парусный спорт': faShip,
    'Museum': faLandmark,
    'Утюг': faChair,
    'Bicycle rental': faBiking,
    'Outdoor furniture': faCouch,
    'Garage': faWarehouse,
    'Закрытый бассейн с подогревом': faThermometerHalf,
    'Beauty salon': faSpa,
    'The bar is equipped for wheelchair access': faWheelchair,
    'DVD-плеер': faCompactDisc,
    'Mini bar': faBeer,
    'Доступ на лыжах к отелю': faSkiing,
    'Телефон': faPhone,
    'Diet menu (on request)': faUtensils,
    'Шкаф/гардероб': faTshirt,
    'Магазины': faShoppingBag,
    'Indoor swimming pool': faSwimmingPool,
    'Gift shop': faGift,
    'Зарядка электромобилей': faPlug,
    'Банк': faUniversity,
    'The spa center': faSpa,
    'Water sports facilities': faSwimmer,
    'Heating': faSnowflake,
    'Доступ в интернет': faWifi,
    'Massage': faSpa,
    'Buffet breakfast': faUtensils,
    'Размещение с домашними животными не допускается': faBan,
    'Ski equipment rental': faSkiing,
    'на китайском': faLanguage,
    'Ironing facilities (on request)': faBroom,
    'Pool facilities': faSwimmer,
    'Conference room': faHandshake,
    'Аптека': faClinicMedical,
    'Computer': faDesktop,
    'Аптечка первой помощи': faFirstAid,
    'Toiletries': faSoap,
    'Фитнес': faDumbbell,
    'Факс': faFax,
    'на японском': faLanguage,
    'Swimming pool': faSwimmingPool,
    'Бадминтон': faTableTennis,
    'Facilities for guests with reduced mobility': faWheelchair,
    'Temperature control for staff': faThermometerHalf,
    'Только для взрослых': faUser,
    'Additional measures against COVID-19': faShieldVirus,
    'Бизнес-центр': faBusinessTime,
    'Free shuttle service': faShuttleVan,
    'Бар у бассейна': faCocktail,
    'Transfer to the ski slope': faSkiing,
    'Помещение для хранения лыж': faSkiing,
    'Дизайн-отель': faPaintBrush,
    'Мини-холодильник': faWineBottle,
    'Рядом с пляжем': faUmbrellaBeach,
    'Курение запрещено на всей территории': faBan,
    'Поле для гольфа': faGolfBall,
    'Площадка для барбекю': faBurn,
    'Snack bar': faCookie,
    'Public beach': faUmbrellaBeach,
    'There are elevators for access to the upper floors': faElevator
};

// Usage
export const getIconByAmenity = (amenityName: string) => {
    return amenityIconMap[amenityName] || faMapMarkerAlt;
};
