name: Deploy to Server

on:
  push:
    branches:
      - main  # Запускать на пуш в ветку main
  pull_request:
    branches:
      - main  # Запускать на мердж пулл-реквеста в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Execute remote command
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'bash /home/hotel-booking-aggregator-front/cmd/docker_cleanup_and_restart.sh'
